VulnTypeMap = {
    "sql": "SQL 注入",
    "sql_exception": "SQL 语句异常",
    "eval": "EVAL 代码执行",
    "loadLibrary": "类库加载",
    "command": "命令执行",
    "xxe": "XXE 外部实体加载",
    "directory": "目录遍历",
    "rename": "文件重命名",
    "readFile": "任意文件下载",
    "deleteFile": "任意文件删除",
    "include": "任意文件包含",
    "writeFile": "任意文件写入",
    "ssrf": "SSRF 服务端请求伪造",
    "ognl": "OGNL 代码执行",
    "webdav": "任意文件上传 (PUT)",
    "fileUpload": "任意文件上传",
    "deserialization": "Transformer 反序列化",
    "xss_echo": "Echo XSS 跨站脚本攻击",
    "xss_userinput": "BODY XSS 跨站脚本攻击",
    "webshell_callable": "WebShell - 变形后门",
    "webshell_eval": "WebShell - 中国菜刀",
    "webshell_command": "WebShell - 命令执行",
    "webshell_file_put_contents": "WebShell - 后门上传",
    "webshell_ld_preload": "WebShell - LD_PRELOAD 后门",
    "response": "HTTP 响应采样检测",
    "link": "文件链接",
    "jndi": "JNDI远程加载",
    "dns": "DNS请求",
}


VulnStatusMap = {
    "log": "新记录",
    "ignore": "忽略",
    "fixed": "已修复",
    "handled": "已处理",
    "unhandled": "未处理",
    "unknown": "未知",
    "false_positive": "误报",
    "false_negative": "漏报",
    "recheck": "待复核",
    "recheck_ignore": "待复核忽略",
    "recheck_false_positive": "待复核误报",
    "recheck_false_negative": "待复核漏报",
}
