# Generated by Django 5.0 on 2024-01-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('data_hash', models.CharField(max_length=63, unique=True)),
                ('scan_status', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
            options={
                'db_table': 'icloud_iast_flow',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_name', models.CharField(max_length=63)),
                ('description', models.TextField()),
                ('rasp_result_list', models.TextField()),
                ('payload_seq', models.CharField(max_length=63, unique=True)),
                ('message', models.TextField()),
                ('time', models.IntegerField()),
                ('upload', models.IntegerField()),
            ],
            options={
                'db_table': 'icloud_iast_report',
            },
        ),
    ]
