# Generated by Django 5.0 on 2024-01-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='scan_status',
            field=models.BooleanField(default=False),
        ),
    ]
