# Generated by Django 5.0 on 2024-03-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iast', '0004_remove_iastscanner_create_time_iastscanner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='iastscanner',
            name='last_time',
            field=models.IntegerField(default=0),
        ),
    ]
