# Generated by Django 5.0 on 2024-03-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iast', '0006_rename_last_time_iastscanner_heartbeat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iastscanner',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
