# Generated by Django 5.0 on 2024-03-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iast', '0007_alter_iastscanner_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iastscanner',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='iastscanner',
            unique_together={('app_id', 'url')},
        ),
    ]
