# Generated by Django 5.0 on 2024-03-03 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controller', '0002_add_default_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='IastScannerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_id', models.CharField(max_length=128)),
                ('rasp_id', models.CharField(max_length=20)),
                ('app_id', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=20)),
                ('event_time', models.CharField(max_length=50)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('request_method', models.CharField(max_length=10)),
                ('intercept_state', models.CharField(max_length=10)),
                ('target', models.CharField(max_length=255)),
                ('server_hostname', models.CharField(max_length=255)),
                ('server_ip', models.CharField(max_length=128)),
                ('server_type', models.CharField(max_length=50)),
                ('server_version', models.CharField(max_length=50)),
                ('server_nic', models.JSONField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('attack_type', models.CharField(max_length=50)),
                ('attack_params', models.JSONField()),
                ('attack_source', models.CharField(max_length=128)),
                ('client_ip', models.CharField(max_length=128)),
                ('plugin_name', models.CharField(max_length=50)),
                ('plugin_confidence', models.IntegerField()),
                ('plugin_message', models.TextField()),
                ('plugin_algorithm', models.TextField()),
                ('header', models.JSONField()),
                ('stack_trace', models.TextField()),
                ('body', models.TextField()),
                ('count', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'icloud_iast_vuln',
                'unique_together': {('rasp_id', 'request_id')},
            },
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('upload_time', models.BigIntegerField()),
                ('version', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('md5', models.CharField(max_length=128)),
                ('origin_content', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('default_algorithm_config', models.JSONField(blank=True, null=True)),
                ('algorithm_config', models.JSONField(blank=True, null=True)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.app')),
            ],
        ),
        migrations.CreateModel(
            name='Rasp',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('strateg_id', models.CharField(max_length=255)),
                ('selected_plugin_id', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('register_ip', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('language_version', models.CharField(max_length=255)),
                ('server_type', models.CharField(max_length=255)),
                ('server_version', models.CharField(max_length=255)),
                ('rasp_home', models.CharField(max_length=255)),
                ('plugin_version', models.CharField(max_length=255)),
                ('plugin_name', models.CharField(max_length=255)),
                ('plugin_md5', models.CharField(max_length=255)),
                ('host_type', models.CharField(blank=True, max_length=255, null=True)),
                ('heartbeat_interval', models.IntegerField()),
                ('online', models.BooleanField(default=True)),
                ('last_heartbeat_time', models.BigIntegerField(blank=True, null=True)),
                ('register_time', models.BigIntegerField(blank=True, null=True)),
                ('environ', models.JSONField(blank=True, null=True)),
                ('description', models.TextField()),
                ('hostname_list', models.JSONField(blank=True, null=True)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.app')),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.JSONField(blank=True, null=True)),
                ('create_time', models.BigIntegerField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('register_ip', models.CharField(blank=True, max_length=32, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('search_string', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.app')),
                ('rasp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.rasp')),
            ],
        ),
    ]
