# Generated by Django 5.0 on 2024-03-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_remove_iastscannerevent_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='iastscannerevent',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
