# Generated by Django 5.0 on 2024-03-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_iastscannerevent_attack_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='iastscannerevent',
            name='vuln_state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
