# Generated by Django 5.0 on 2024-01-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("secret", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("config_time", models.DateTimeField(auto_now_add=True)),
                ("selected_plugin_id", models.CharField(max_length=255)),
                ("general_config", models.JSONField(blank=True, null=True)),
                ("whitelist_config", models.JSONField(blank=True, null=True)),
                ("attack_type_alarm_conf", models.JSONField(blank=True, null=True)),
                ("email_alarm_conf", models.JSONField(blank=True, null=True)),
                ("ding_alarm_conf", models.JSONField(blank=True, null=True)),
                ("http_alarm_conf", models.JSONField(blank=True, null=True)),
                ("algorithm_config", models.JSONField(blank=True, null=True)),
                ("general_alarm_conf", models.JSONField(blank=True, null=True)),
                ("kafka_alarm_conf", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
