# Generated by Django 5.0 on 2024-01-01 14:36

import json
from django.db import migrations
from django.utils import timezone


def add_initial_records(apps, schema_editor):
    # 获取你的模型
    default_app = apps.get_model("controller", "App")

    # 创建一条默认记录
    default_record = default_app(
        id="47014b167a616f646a788a6d9eb4a1a29ca98dda",
        name="Default",
        secret="1UDTwKcN1ak0smftbSyrDPpLOGUz5coIxAUmf0r9ZsEa",
        language="Java",
        description="This is an default app.",
        create_time=timezone.now(),
        config_time=timezone.now(),
        general_config=json.dumps({"config1": "value1"}),
        whitelist_config=json.dumps([{"configItem1": "value1"}]),
        selected_plugin_id="plugin-id",
        attack_type_alarm_conf=json.dumps({"attackType": ["alarmType1", "alarmType2"]}),
        email_alarm_conf=json.dumps({"email": "example@example.com"}),
        ding_alarm_conf=json.dumps({"ding": "dingValue"}),
        http_alarm_conf=json.dumps({"http": "httpValue"}),
        algorithm_config=json.dumps({"algorithm1": "value1"}),
        general_alarm_conf=json.dumps({"generalAlarm": "value1"}),
        kafka_alarm_conf=json.dumps({"kafka": "value1"}),
    )
    default_record.save()

    # 创建一条测试记录
    test_record = default_app(
        id="63d3ada891a0da74b6fabf05d356279d1a3568a9",
        name="Test",
        secret="mlgC3YXUJW5fU5q9PkENdyPSyd8VvNQP3udYcPD05yUa",
        language="Java",
        description="This is an default app.",
        create_time=timezone.now(),
        config_time=timezone.now(),
        general_config=json.dumps({"config1": "value1"}),
        whitelist_config=json.dumps([{"configItem1": "value1"}]),
        selected_plugin_id="plugin-id",
        attack_type_alarm_conf=json.dumps({"attackType": ["alarmType1", "alarmType2"]}),
        email_alarm_conf=json.dumps({"email": "example@example.com"}),
        ding_alarm_conf=json.dumps({"ding": "dingValue"}),
        http_alarm_conf=json.dumps({"http": "httpValue"}),
        algorithm_config=json.dumps({"algorithm1": "value1"}),
        general_alarm_conf=json.dumps({"generalAlarm": "value1"}),
        kafka_alarm_conf=json.dumps({"kafka": "value1"}),
    )
    test_record.save()


class Migration(migrations.Migration):
    dependencies = [
        ("controller", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_initial_records),
    ]
