# Generated by Django 5.0 on 2024-03-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='setting',
            table='icloud_controller_setting',
        ),
    ]
