# Generated by Django 5.0 on 2024-03-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_alter_setting_name_alter_setting_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='app',
            table='icloud_controller_app',
        ),
    ]
